version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tw
      POSTGRES_PASSWORD: tw
      POSTGRES_USER: tw
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./docker/postgres:/var/lib/postgres
volumes:
  postgres:
    driver: local
